# Generated by Django 5.2.7 on 2025-11-04
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_topup'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup',
            name='credited_at',
            field=models.DateTimeField(blank=True, help_text='Kdy byly připsány kredity (po potvrzení).', null=True),
        ),
    ]
