# Generated by Django 5.1.1 on 2025-11-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_topup_credited_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Čeká na potvrzení"),
                    ("confirmed", "Potvrzeno"),
                    ("cancelled", "Zrušeno"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="topup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="topup",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Čeká na platbu"),
                    ("confirmed", "Připsáno"),
                    ("cancelled", "Zrušeno"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
    ]
