# Generated by Django 5.1.1 on 2025-11-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("instructor", "Lektor"), ("client", "Klient")],
                default="client",
                max_length=10,
            ),
        ),
    ]
