# Generated by Django 5.1.1 on 2025-11-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="category",
            field=models.CharField(
                choices=[
                    ("yoga", "Jóga"),
                    ("cardio", "Cardio"),
                    ("strength", "Silový trénink"),
                    ("pilates", "Pilates"),
                    ("stretch", "Stretch/rozcvička"),
                    ("other", "Jiné"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
