# Generated by Django 5.1.1 on 2025-11-02 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_lesson_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="Datum konání lekce"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="location",
            field=models.CharField(
                default="Fitness centrum",
                help_text="Místo konání lekce",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="start_time",
            field=models.TimeField(default="09:00", help_text="Čas začátku lekce"),
        ),
    ]
