# Generated by Django 5.1.1 on 2025-11-05 15:52

import django.db.models.deletion
from django.db import migrations, models


def create_categories_and_migrate_data(apps, schema_editor):
    """
    Vytvoří Category objekty podle starých choices hodnot
    a namapuje existující Lesson záznamy.
    """
    Category = apps.get_model('bookings', 'Category')
    Lesson = apps.get_model('bookings', 'Lesson')
    
    # Staré choices - vytvoříme z nich Category záznamy
    OLD_CATEGORIES = [
        ('yoga', 'Jóga', 1),
        ('pilates', 'Pilates', 2),
        ('cardio', 'Cardio', 3),
        ('strength', 'Silový trénink', 4),
        ('stretch', 'Stretch/rozcvička', 5),
        ('other', 'Jiné', 6),
    ]
    
    category_map = {}
    for slug, name, order in OLD_CATEGORIES:
        cat, created = Category.objects.get_or_create(
            slug=slug,
            defaults={'name': name, 'order': order}
        )
        category_map[slug] = cat
    
    # Přečteme hodnoty ze starého pole category_old (které je teď CharField)
    # a namapujeme je na nové FK category_new
    for lesson in Lesson.objects.all():
        old_value = getattr(lesson, 'category_old', None)
        if old_value and old_value in category_map:
            lesson.category_new = category_map[old_value]
            lesson.save(update_fields=['category_new'])


def reverse_migration(apps, schema_editor):
    """Zpětná migrace - smaže Category záznamy."""
    Category = apps.get_model('bookings', 'Category')
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_lesson_date_lesson_location_lesson_start_time"),
    ]

    operations = [
        # Krok 1: Vytvoř model Category
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Název kategorie"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Slug (URL)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Popis")),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Nižší číslo = dříve v seznamu",
                        verbose_name="Pořadí",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorie",
                "ordering": ["order", "name"],
            },
        ),
        
        # Krok 2: Přejmenuj staré pole category na category_old
        migrations.RenameField(
            model_name='lesson',
            old_name='category',
            new_name='category_old',
        ),
        
        # Krok 3: Přidej nové FK pole category_new
        migrations.AddField(
            model_name='lesson',
            name='category_new',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='lessons',
                to='bookings.category',
                verbose_name='Kategorie',
            ),
        ),
        
        # Krok 4: Datová migrace - vytvoř Category a namapuj
        migrations.RunPython(create_categories_and_migrate_data, reverse_migration),
        
        # Krok 5: Smaž staré pole category_old
        migrations.RemoveField(
            model_name='lesson',
            name='category_old',
        ),
        
        # Krok 6: Přejmenuj category_new na category
        migrations.RenameField(
            model_name='lesson',
            old_name='category_new',
            new_name='category',
        ),
    ]
