# Generated by Django 5.1.1 on 2025-11-06 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_category_alter_lesson_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Čeká na potvrzení"),
                    ("confirmed", "Potvrzeno"),
                    ("cancelled", "Zrušeno"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="start_time",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "created_at"], name="bookings_bo_status_72dd85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["start_time", "is_available"],
                name="bookings_ti_start_t_62b37e_idx",
            ),
        ),
    ]
